typography_spectrum: 0.10664376663044095
content_rating:
  adult: false
color:
  brandStrength: 0.9908715367782861
  lightness: 0.23487555561587214
  saturation: 0.8575708828866482
  rhythmicContrast: 0.8570681572891772
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
opengraph:
  image: null
layout_spectrum: 0.7464755873661488
author:
  name: Shawn
  email: shawn@creativemovers.com
  url: www.creativemoversrecruiting.com
logo: null
name: Creative Movers Recruiting
navigation:
  - name: Creative Movers
    url: www.creativemovers.com
    type: external
title: Creative Jobs/Creative Industries
description: Experienced & Personal Recruiting Services
